#!/usr/bin/env bash
# setup.sh — SendDock self-host installer for Ubuntu and Arch Linux.
#
# Installs Docker (if missing), downloads the official compose file,
# generates a .env with random secrets, and starts the stack
# (senddock + postgres + redis).
#
# Install:
#   curl -fsSL https://raw.githubusercontent.com/Arkhe-Systems/senddock/main/scripts/setup.sh | sudo bash
#
# The installer asks nothing. Your public URL, SMTP and license key are
# configured from the dashboard the first time you open SendDock.
#
# Environment overrides:
#   INSTALL_DIR                install directory (default: /opt/senddock)
#   SENDDOCK_PORT              host port to expose (default: 8080)
#   SENDDOCK_PUBLIC_URL        deprecated — seeds PUBLIC_URL in .env for
#                              scripted installs. Removed in v0.9; set the
#                              public URL from the dashboard instead.

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/senddock}"
SENDDOCK_PORT="${SENDDOCK_PORT:-8080}"
COMPOSE_URL="https://raw.githubusercontent.com/Arkhe-Systems/senddock/main/docker-compose.image.yml"

if [[ -t 1 ]]; then
  b=$(printf '\033[1m'); g=$(printf '\033[32m')
  y=$(printf '\033[33m'); r=$(printf '\033[31m'); n=$(printf '\033[0m')
else
  b=""; g=""; y=""; r=""; n=""
fi

say()  { echo "${b}==>${n} $*"; }
ok()   { echo "${g}✓${n} $*"; }
warn() { echo "${y}!${n} $*" >&2; }
die()  { echo "${r}✗ $*${n}" >&2; exit 1; }

# --- preflight ---------------------------------------------------------------

[[ "$(uname -s)" == "Linux" ]] || die "This installer only supports Linux."

[[ -r /etc/os-release ]] || die "Can't read /etc/os-release — unsupported distribution."
# shellcheck disable=SC1091
. /etc/os-release

case "${ID:-}" in
  ubuntu)
    FAMILY="ubuntu"
    ;;
  arch|manjaro|endeavouros|cachyos|garuda)
    FAMILY="arch"
    ;;
  *)
    case "${ID_LIKE:-}" in
      *arch*) FAMILY="arch" ;;
      *) die "This installer supports Ubuntu and Arch-based distros (detected: ${PRETTY_NAME:-unknown}). For other distros, see https://docs.senddock.dev/self-hosting/installation" ;;
    esac
    ;;
esac

[[ $EUID -eq 0 ]] || die "Run with sudo: sudo bash setup.sh"

ensure_pkg() {
  local pkg="$1"
  command -v "$pkg" >/dev/null 2>&1 && return 0
  say "Installing missing dependency: $pkg"
  case "$FAMILY" in
    ubuntu) apt-get update -qq && apt-get install -y -qq "$pkg" ;;
    arch)   pacman -Sy --noconfirm --needed "$pkg" ;;
  esac
}

for cmd in curl openssl; do
  ensure_pkg "$cmd"
done

# --- Docker ------------------------------------------------------------------

install_docker() {
  say "Installing Docker…"
  case "$FAMILY" in
    ubuntu)
      apt-get update -qq
      apt-get install -y -qq ca-certificates curl gnupg
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
        > /etc/apt/sources.list.d/docker.list
      apt-get update -qq
      apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ;;
    arch)
      pacman -Sy --noconfirm --needed docker docker-buildx docker-compose
      ;;
  esac
  systemctl enable --now docker
  ok "Docker installed."
}

docker_ready() {
  command -v docker >/dev/null 2>&1 \
    && docker compose version >/dev/null 2>&1 \
    && docker info >/dev/null 2>&1
}

if docker_ready; then
  ok "Docker already installed and running ($(docker --version))."
elif command -v docker >/dev/null 2>&1; then
  warn "Docker CLI present but daemon not reachable — trying to start it…"
  systemctl enable --now docker 2>/dev/null || true
  sleep 3
  if docker_ready; then
    ok "Docker daemon started ($(docker --version))."
  else
    warn "Daemon still not reachable — reinstalling Docker…"
    install_docker
  fi
else
  install_docker
fi

# --- install dir + compose ---------------------------------------------------

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
say "Install dir: $INSTALL_DIR"

if [[ -f docker-compose.yml ]]; then
  warn "docker-compose.yml already exists — keeping the existing file."
else
  say "Downloading docker-compose.yml…"
  curl -fsSL "$COMPOSE_URL" -o docker-compose.yml
  ok "docker-compose.yml ready."
fi

# --- .env --------------------------------------------------------------------

if [[ -f .env ]]; then
  ok ".env already exists — leaving it untouched (secrets preserved)."
else
  say "Generating .env with random secrets…"
  JWT_SECRET="$(openssl rand -hex 32)"
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  SENDDOCK_WATCHTOWER_TOKEN="$(openssl rand -hex 32)"

  (
  umask 077
  cat > .env <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Secrets and host wiring. Everything else is configured from the dashboard.

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}

SENDDOCK_WATCHTOWER_URL=http://watchtower:8080
SENDDOCK_WATCHTOWER_TOKEN=${SENDDOCK_WATCHTOWER_TOKEN}

SENDDOCK_PORT=${SENDDOCK_PORT}

# Pro / Team license key from senddock.dev. Empty = Community tier (free).
# Paste your key here and run: docker compose up -d
SENDDOCK_LICENSE_KEY=
EOF
  )
  chmod 600 .env
  ok ".env written (mode 600)."
fi

ensure_env_var() {
  local key="$1" value="$2"
  if grep -qE "^${key}=" .env; then
    return 0
  fi
  printf '%s=%s\n' "$key" "$value" >> .env
  ok "Added missing ${key} to .env"
}

ensure_env_var SENDDOCK_WATCHTOWER_URL "http://watchtower:8080"
ensure_env_var SENDDOCK_WATCHTOWER_TOKEN "$(openssl rand -hex 32)"

if [[ -n "${SENDDOCK_PUBLIC_URL:-}" ]]; then
  warn "SENDDOCK_PUBLIC_URL is deprecated — the public URL is now set from the dashboard and will be removed from .env in v0.9."
  if grep -qE '^PUBLIC_URL=' .env; then
    sed -i "s|^PUBLIC_URL=.*|PUBLIC_URL=${SENDDOCK_PUBLIC_URL}|" .env
  else
    echo "PUBLIC_URL=${SENDDOCK_PUBLIC_URL}" >> .env
  fi
  ok "Seeded PUBLIC_URL = ${SENDDOCK_PUBLIC_URL}"
fi

# --- docker-compose.override.yml (Watchtower) -------------------------------

if [[ -f docker-compose.override.yml ]]; then
  warn "docker-compose.override.yml already exists — keeping the existing file."
else
  say "Writing docker-compose.override.yml (Watchtower for one-click updates)…"
  cat > docker-compose.override.yml <<'EOF'
# Generated by setup.sh — adds Watchtower so the dashboard's "Update now"
# button can pull the new image and recreate the SendDock container.
#
# Watchtower runs in HTTP-API-only mode (no auto-polling). Updates only
# fire when you click the button in the dashboard.
#
# Scope is limited to containers with the watchtower.enable label, so
# Watchtower only ever touches the SendDock container — not your other
# services on the same Docker host.
#
# To opt out: delete this file, remove the two SENDDOCK_WATCHTOWER_* lines
# from .env, then run `docker compose up -d`. Updates will revert to the
# manual `docker compose pull && up -d` flow.

services:
  watchtower:
    # Maintained fork of containrrr/watchtower. The upstream was abandoned in
    # 2023; its :latest image ships a Docker client too old for modern daemons
    # (API < 1.40) and crashes in a restart loop on Ubuntu 24.04+/Docker 26+.
    image: nickfedor/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_TOKEN: ${SENDDOCK_WATCHTOWER_TOKEN:?SENDDOCK_WATCHTOWER_TOKEN is required in .env}
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: "false"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"

  senddock:
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      SENDDOCK_WATCHTOWER_URL: ${SENDDOCK_WATCHTOWER_URL:-http://watchtower:8080}
      SENDDOCK_WATCHTOWER_TOKEN: ${SENDDOCK_WATCHTOWER_TOKEN:?SENDDOCK_WATCHTOWER_TOKEN is required in .env}
EOF
  ok "docker-compose.override.yml ready."
fi

# --- bring up ----------------------------------------------------------------

say "Pulling images…"
docker compose pull

say "Starting the stack…"
docker compose up -d

# --- post-up health check ---------------------------------------------------

say "Waiting up to 60s for all services to stabilize…"
all_good=0
for i in 1 2 3 4 5 6 7 8 9 10 11 12; do
  sleep 5
  running=$(docker compose ps --status running --quiet 2>/dev/null | wc -l | tr -d ' ')
  total=$(docker compose ps --quiet 2>/dev/null | wc -l | tr -d ' ')
  if [[ "$total" -gt 0 && "$running" == "$total" ]]; then
    all_good=1
    break
  fi
done

if [[ $all_good -eq 1 ]]; then
  ok "All $total services running."
else
  warn "Some services are not in 'running' state after 60s."
  warn "Inspect with:"
  warn "    cd ${INSTALL_DIR} && sudo docker compose ps"
  warn "    cd ${INSTALL_DIR} && sudo docker compose logs --tail=50"
fi

echo ""
docker compose ps

# --- final ------------------------------------------------------------------

host_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
dashboard_url="${SENDDOCK_PUBLIC_URL:-}"
if [[ -z "$dashboard_url" ]]; then
  if [[ -n "$host_ip" ]]; then
    dashboard_url="http://${host_ip}:${SENDDOCK_PORT}"
  else
    dashboard_url="http://<your-server-ip>:${SENDDOCK_PORT}"
  fi
fi

cat <<EOF

${g}${b}SendDock is starting.${n}

  Install dir: ${INSTALL_DIR}
  Compose:     ${INSTALL_DIR}/docker-compose.yml + docker-compose.override.yml
  Env:         ${INSTALL_DIR}/.env  (mode 600 — contains secrets)

${b}Next steps${n}

  1. Wait ~10s for the healthcheck:
       cd ${INSTALL_DIR} && docker compose ps

  2. Open SendDock and create your admin account on the Setup screen:
       ${dashboard_url}

     The Setup screen also asks for your public URL — the address your emails'
     unsubscribe and tracking links will point at. You can change it later
     under Instance in the dashboard.

  3. For production, put a reverse proxy with HTTPS in front (Caddy / Nginx / Traefik).
     Guide: https://docs.senddock.dev/self-hosting/installation#reverse-proxy-https

  4. Configure your SMTP relay from the dashboard (Settings → SMTP).

     A Pro / Team license key is the one thing still set by hand: paste it into
     SENDDOCK_LICENSE_KEY in ${INSTALL_DIR}/.env and run:
       cd ${INSTALL_DIR} && docker compose up -d

     If "Test Connection" times out, your ISP (residential connections especially)
     may block outbound SMTP ports. See the diagnostic + workarounds at:
       https://docs.senddock.dev/guide/smtp#diagnosing-port-issues

${b}Updates${n}

  When a new SendDock release lands, an "Update available" badge appears in
  the dashboard nav. Click it → "Update now" → Watchtower pulls the new
  image and recreates the container. Postgres + Redis volumes are preserved
  (your data stays). Takes ~30–60s.

  Note: Watchtower mounts /var/run/docker.sock and is therefore root-equivalent
  on the host. It's label-scoped to only ever touch the SendDock container —
  not your other services. To opt out, see docker-compose.override.yml.

EOF
