// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO audit_log (project_id, user_id, action, target_type, target_id, metadata, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, user_id, action, target_type, target_id, metadata, ip_address, user_agent, created_at
`

type CreateAuditEntryParams struct {
	ProjectID  uuid.NullUUID
	UserID     uuid.NullUUID
	Action     string
	TargetType sql.NullString
	TargetID   sql.NullString
	Metadata   json.RawMessage
	IpAddress  pqtype.Inet
	UserAgent  sql.NullString
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditEntry,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
