// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcast_jobs.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const bulkInsertBroadcastJobs = `-- name: BulkInsertBroadcastJobs :exec
INSERT INTO broadcast_jobs (broadcast_id, project_id, subscriber_id, recipient_email)
SELECT
    $1::uuid,
    $2::uuid,
    (j->>'subscriber_id')::uuid,
    j->>'recipient_email'
FROM jsonb_array_elements($3::jsonb) AS j
`

type BulkInsertBroadcastJobsParams struct {
	BroadcastID uuid.UUID
	ProjectID   uuid.UUID
	Jobs        json.RawMessage
}

func (q *Queries) BulkInsertBroadcastJobs(ctx context.Context, arg BulkInsertBroadcastJobsParams) error {
	_, err := q.db.ExecContext(ctx, bulkInsertBroadcastJobs, arg.BroadcastID, arg.ProjectID, arg.Jobs)
	return err
}

const claimBroadcastJob = `-- name: ClaimBroadcastJob :one
UPDATE broadcast_jobs SET
    status = 'sending',
    attempts = attempts + 1
WHERE id = (
    SELECT id FROM broadcast_jobs
    WHERE status IN ('pending', 'retry')
      AND scheduled_at <= NOW()
    ORDER BY scheduled_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, broadcast_id, project_id, subscriber_id, recipient_email, status, attempts, last_error, scheduled_at, completed_at, created_at
`

func (q *Queries) ClaimBroadcastJob(ctx context.Context) (BroadcastJob, error) {
	row := q.db.QueryRowContext(ctx, claimBroadcastJob)
	var i BroadcastJob
	err := row.Scan(
		&i.ID,
		&i.BroadcastID,
		&i.ProjectID,
		&i.SubscriberID,
		&i.RecipientEmail,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ScheduledAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveBroadcastJobs = `-- name: CountActiveBroadcastJobs :one
SELECT COUNT(*) FROM broadcast_jobs
WHERE status IN ('pending', 'retry', 'sending')
`

func (q *Queries) CountActiveBroadcastJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBroadcastJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBroadcastJobsRemaining = `-- name: CountBroadcastJobsRemaining :one
SELECT COUNT(*) FROM broadcast_jobs
WHERE broadcast_id = $1
  AND status IN ('pending', 'retry', 'sending')
`

func (q *Queries) CountBroadcastJobsRemaining(ctx context.Context, broadcastID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBroadcastJobsRemaining, broadcastID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markBroadcastJobBounced = `-- name: MarkBroadcastJobBounced :exec
UPDATE broadcast_jobs SET
    status = 'bounced',
    completed_at = NOW(),
    last_error = $1::text
WHERE id = $2
`

type MarkBroadcastJobBouncedParams struct {
	LastError string
	ID        uuid.UUID
}

func (q *Queries) MarkBroadcastJobBounced(ctx context.Context, arg MarkBroadcastJobBouncedParams) error {
	_, err := q.db.ExecContext(ctx, markBroadcastJobBounced, arg.LastError, arg.ID)
	return err
}

const markBroadcastJobFailed = `-- name: MarkBroadcastJobFailed :exec
UPDATE broadcast_jobs SET
    status = 'failed',
    completed_at = NOW(),
    last_error = $1::text
WHERE id = $2
`

type MarkBroadcastJobFailedParams struct {
	LastError string
	ID        uuid.UUID
}

func (q *Queries) MarkBroadcastJobFailed(ctx context.Context, arg MarkBroadcastJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, markBroadcastJobFailed, arg.LastError, arg.ID)
	return err
}

const markBroadcastJobSent = `-- name: MarkBroadcastJobSent :exec
UPDATE broadcast_jobs SET
    status = 'sent',
    completed_at = NOW(),
    last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkBroadcastJobSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markBroadcastJobSent, id)
	return err
}

const markBroadcastJobSuppressed = `-- name: MarkBroadcastJobSuppressed :exec
UPDATE broadcast_jobs SET
    status = 'suppressed',
    completed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkBroadcastJobSuppressed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markBroadcastJobSuppressed, id)
	return err
}

const resetStuckSendingJobs = `-- name: ResetStuckSendingJobs :execrows
UPDATE broadcast_jobs SET
    status = 'retry',
    scheduled_at = NOW()
WHERE status = 'sending'
`

func (q *Queries) ResetStuckSendingJobs(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetStuckSendingJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const scheduleBroadcastJobRetry = `-- name: ScheduleBroadcastJobRetry :exec
UPDATE broadcast_jobs SET
    status = 'retry',
    scheduled_at = $1,
    last_error = $2::text
WHERE id = $3
`

type ScheduleBroadcastJobRetryParams struct {
	ScheduledAt time.Time
	LastError   string
	ID          uuid.UUID
}

func (q *Queries) ScheduleBroadcastJobRetry(ctx context.Context, arg ScheduleBroadcastJobRetryParams) error {
	_, err := q.db.ExecContext(ctx, scheduleBroadcastJobRetry, arg.ScheduledAt, arg.LastError, arg.ID)
	return err
}
