// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcasts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countBroadcastsByProject = `-- name: CountBroadcastsByProject :one
SELECT COUNT(*) FROM broadcasts WHERE project_id = $1
`

func (q *Queries) CountBroadcastsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBroadcastsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBroadcast = `-- name: CreateBroadcast :one
INSERT INTO broadcasts (project_id, template_id, subject, variables, total_recipients)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, template_id, subject, variables, status, total_recipients, sent_count, failed_count, suppressed_count, started_at, finished_at
`

type CreateBroadcastParams struct {
	ProjectID       uuid.UUID
	TemplateID      uuid.UUID
	Subject         string
	Variables       json.RawMessage
	TotalRecipients int32
}

func (q *Queries) CreateBroadcast(ctx context.Context, arg CreateBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRowContext(ctx, createBroadcast,
		arg.ProjectID,
		arg.TemplateID,
		arg.Subject,
		arg.Variables,
		arg.TotalRecipients,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Subject,
		&i.Variables,
		&i.Status,
		&i.TotalRecipients,
		&i.SentCount,
		&i.FailedCount,
		&i.SuppressedCount,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBroadcast = `-- name: GetBroadcast :one
SELECT id, project_id, template_id, subject, variables, status, total_recipients, sent_count, failed_count, suppressed_count, started_at, finished_at FROM broadcasts WHERE id = $1 AND project_id = $2
`

type GetBroadcastParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetBroadcast(ctx context.Context, arg GetBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRowContext(ctx, getBroadcast, arg.ID, arg.ProjectID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Subject,
		&i.Variables,
		&i.Status,
		&i.TotalRecipients,
		&i.SentCount,
		&i.FailedCount,
		&i.SuppressedCount,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const incrementBroadcastFailed = `-- name: IncrementBroadcastFailed :exec
UPDATE broadcasts SET failed_count = failed_count + 1 WHERE id = $1
`

func (q *Queries) IncrementBroadcastFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementBroadcastFailed, id)
	return err
}

const incrementBroadcastSent = `-- name: IncrementBroadcastSent :exec
UPDATE broadcasts SET sent_count = sent_count + 1 WHERE id = $1
`

func (q *Queries) IncrementBroadcastSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementBroadcastSent, id)
	return err
}

const incrementBroadcastSuppressed = `-- name: IncrementBroadcastSuppressed :exec
UPDATE broadcasts SET suppressed_count = suppressed_count + 1 WHERE id = $1
`

func (q *Queries) IncrementBroadcastSuppressed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementBroadcastSuppressed, id)
	return err
}

const listBroadcastsByProject = `-- name: ListBroadcastsByProject :many
SELECT id, project_id, template_id, subject, variables, status, total_recipients, sent_count, failed_count, suppressed_count, started_at, finished_at FROM broadcasts
WHERE project_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListBroadcastsByProjectParams struct {
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListBroadcastsByProject(ctx context.Context, arg ListBroadcastsByProjectParams) ([]Broadcast, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcastsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Broadcast
	for rows.Next() {
		var i Broadcast
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Subject,
			&i.Variables,
			&i.Status,
			&i.TotalRecipients,
			&i.SentCount,
			&i.FailedCount,
			&i.SuppressedCount,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBroadcastCompleted = `-- name: MarkBroadcastCompleted :exec
UPDATE broadcasts SET status = 'completed', finished_at = NOW() WHERE id = $1
`

func (q *Queries) MarkBroadcastCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markBroadcastCompleted, id)
	return err
}

const markInProgressBroadcastsInterrupted = `-- name: MarkInProgressBroadcastsInterrupted :exec
UPDATE broadcasts SET status = 'interrupted', finished_at = NOW() WHERE status = 'sending'
`

func (q *Queries) MarkInProgressBroadcastsInterrupted(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markInProgressBroadcastsInterrupted)
	return err
}
