// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimCampaignForExecution = `-- name: ClaimCampaignForExecution :execrows
UPDATE campaigns SET status = 'sending'
WHERE id = $1 AND status = 'scheduled'
`

func (q *Queries) ClaimCampaignForExecution(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimCampaignForExecution, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (project_id, template_id, name, subject, scheduled_at, variables, newsletter_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, template_id, name, status, scheduled_at, sent_at, sent_count, failed_count, created_at, variables, subject, broadcast_id, newsletter_id
`

type CreateCampaignParams struct {
	ProjectID    uuid.UUID
	TemplateID   uuid.UUID
	Name         string
	Subject      string
	ScheduledAt  time.Time
	Variables    json.RawMessage
	NewsletterID uuid.NullUUID
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.ProjectID,
		arg.TemplateID,
		arg.Name,
		arg.Subject,
		arg.ScheduledAt,
		arg.Variables,
		arg.NewsletterID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.SentCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.Variables,
		&i.Subject,
		&i.BroadcastID,
		&i.NewsletterID,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :execrows
DELETE FROM campaigns WHERE id = $1 AND project_id = $2
`

type DeleteCampaignParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCampaign, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT
    c.id, c.project_id, c.template_id, c.name, c.subject,
    c.scheduled_at, c.sent_at, c.created_at, c.status,
    COALESCE(b.sent_count, c.sent_count)::int AS sent_count,
    COALESCE(b.failed_count, c.failed_count)::int AS failed_count,
    c.variables,
    c.broadcast_id
FROM campaigns c
LEFT JOIN broadcasts b ON b.id = c.broadcast_id
WHERE c.id = $1 AND c.project_id = $2
`

type GetCampaignByIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

type GetCampaignByIDRow struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	TemplateID  uuid.UUID
	Name        string
	Subject     string
	ScheduledAt time.Time
	SentAt      sql.NullTime
	CreatedAt   time.Time
	Status      string
	SentCount   int32
	FailedCount int32
	Variables   json.RawMessage
	BroadcastID uuid.NullUUID
}

func (q *Queries) GetCampaignByID(ctx context.Context, arg GetCampaignByIDParams) (GetCampaignByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, arg.ID, arg.ProjectID)
	var i GetCampaignByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Subject,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.Status,
		&i.SentCount,
		&i.FailedCount,
		&i.Variables,
		&i.BroadcastID,
	)
	return i, err
}

const getPendingCampaigns = `-- name: GetPendingCampaigns :many
SELECT id, project_id, template_id, name, status, scheduled_at, sent_at, sent_count, failed_count, created_at, variables, subject, broadcast_id, newsletter_id FROM campaigns
WHERE status = 'scheduled' AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC
`

func (q *Queries) GetPendingCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, getPendingCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Status,
			&i.ScheduledAt,
			&i.SentAt,
			&i.SentCount,
			&i.FailedCount,
			&i.CreatedAt,
			&i.Variables,
			&i.Subject,
			&i.BroadcastID,
			&i.NewsletterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByProject = `-- name: ListCampaignsByProject :many
SELECT
    c.id, c.project_id, c.template_id, c.name, c.subject,
    c.scheduled_at, c.sent_at, c.created_at, c.status,
    COALESCE(b.sent_count, c.sent_count)::int AS sent_count,
    COALESCE(b.failed_count, c.failed_count)::int AS failed_count,
    c.variables,
    c.broadcast_id
FROM campaigns c
LEFT JOIN broadcasts b ON b.id = c.broadcast_id
WHERE c.project_id = $1
ORDER BY c.created_at DESC
`

type ListCampaignsByProjectRow struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	TemplateID  uuid.UUID
	Name        string
	Subject     string
	ScheduledAt time.Time
	SentAt      sql.NullTime
	CreatedAt   time.Time
	Status      string
	SentCount   int32
	FailedCount int32
	Variables   json.RawMessage
	BroadcastID uuid.NullUUID
}

func (q *Queries) ListCampaignsByProject(ctx context.Context, projectID uuid.UUID) ([]ListCampaignsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsByProjectRow
	for rows.Next() {
		var i ListCampaignsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Subject,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.Status,
			&i.SentCount,
			&i.FailedCount,
			&i.Variables,
			&i.BroadcastID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignDoneFromBroadcast = `-- name: MarkCampaignDoneFromBroadcast :exec
UPDATE campaigns
SET status = 'sent',
    sent_count = b.sent_count,
    failed_count = b.failed_count,
    sent_at = NOW()
FROM broadcasts b
WHERE campaigns.broadcast_id = b.id
  AND b.id = $1
  AND campaigns.status = 'sending'
`

func (q *Queries) MarkCampaignDoneFromBroadcast(ctx context.Context, broadcastID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markCampaignDoneFromBroadcast, broadcastID)
	return err
}

const setCampaignBroadcast = `-- name: SetCampaignBroadcast :exec
UPDATE campaigns SET broadcast_id = $1 WHERE id = $2
`

type SetCampaignBroadcastParams struct {
	BroadcastID uuid.NullUUID
	ID          uuid.UUID
}

func (q *Queries) SetCampaignBroadcast(ctx context.Context, arg SetCampaignBroadcastParams) error {
	_, err := q.db.ExecContext(ctx, setCampaignBroadcast, arg.BroadcastID, arg.ID)
	return err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns SET
    name = $3,
    template_id = $4,
    subject = $5,
    scheduled_at = $6,
    variables = $7,
    newsletter_id = $8
WHERE id = $1 AND project_id = $2 AND status = 'scheduled'
RETURNING id, project_id, template_id, name, status, scheduled_at, sent_at, sent_count, failed_count, created_at, variables, subject, broadcast_id, newsletter_id
`

type UpdateCampaignParams struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	Name         string
	TemplateID   uuid.UUID
	Subject      string
	ScheduledAt  time.Time
	Variables    json.RawMessage
	NewsletterID uuid.NullUUID
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.TemplateID,
		arg.Subject,
		arg.ScheduledAt,
		arg.Variables,
		arg.NewsletterID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.SentCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.Variables,
		&i.Subject,
		&i.BroadcastID,
		&i.NewsletterID,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE campaigns SET
    status = $1::text,
    sent_at = CASE WHEN $1::text = 'sent' THEN NOW() ELSE sent_at END,
    sent_count = $2,
    failed_count = $3
WHERE id = $4
`

type UpdateCampaignStatusParams struct {
	Status      string
	SentCount   int32
	FailedCount int32
	ID          uuid.UUID
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignStatus,
		arg.Status,
		arg.SentCount,
		arg.FailedCount,
		arg.ID,
	)
	return err
}
