// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (project_id, template_id, name, scheduled_at)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, template_id, name, status, scheduled_at, sent_at, sent_count, failed_count, created_at
`

type CreateCampaignParams struct {
	ProjectID   uuid.UUID
	TemplateID  uuid.UUID
	Name        string
	ScheduledAt time.Time
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.ProjectID,
		arg.TemplateID,
		arg.Name,
		arg.ScheduledAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.SentCount,
		&i.FailedCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1 AND project_id = $2 AND status = 'scheduled'
`

type DeleteCampaignParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, arg.ID, arg.ProjectID)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, project_id, template_id, name, status, scheduled_at, sent_at, sent_count, failed_count, created_at FROM campaigns WHERE id = $1 AND project_id = $2
`

type GetCampaignByIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetCampaignByID(ctx context.Context, arg GetCampaignByIDParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, arg.ID, arg.ProjectID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateID,
		&i.Name,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.SentCount,
		&i.FailedCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingCampaigns = `-- name: GetPendingCampaigns :many
SELECT id, project_id, template_id, name, status, scheduled_at, sent_at, sent_count, failed_count, created_at FROM campaigns
WHERE status = 'scheduled' AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC
`

func (q *Queries) GetPendingCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, getPendingCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Status,
			&i.ScheduledAt,
			&i.SentAt,
			&i.SentCount,
			&i.FailedCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByProject = `-- name: ListCampaignsByProject :many
SELECT id, project_id, template_id, name, status, scheduled_at, sent_at, sent_count, failed_count, created_at FROM campaigns
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByProject(ctx context.Context, projectID uuid.UUID) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateID,
			&i.Name,
			&i.Status,
			&i.ScheduledAt,
			&i.SentAt,
			&i.SentCount,
			&i.FailedCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE campaigns SET
    status = $2,
    sent_at = CASE WHEN $2 = 'sent' THEN NOW() ELSE sent_at END,
    sent_count = $3,
    failed_count = $4
WHERE id = $1
`

type UpdateCampaignStatusParams struct {
	ID          uuid.UUID
	Status      string
	SentCount   int32
	FailedCount int32
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignStatus,
		arg.ID,
		arg.Status,
		arg.SentCount,
		arg.FailedCount,
	)
	return err
}
