// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_logs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countEmailLogsByProject = `-- name: CountEmailLogsByProject :one
SELECT COUNT(*) FROM email_logs WHERE project_id = $1
`

func (q *Queries) CountEmailLogsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailLogsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailLogsByStatus = `-- name: CountEmailLogsByStatus :one
SELECT COUNT(*) FROM email_logs WHERE project_id = $1 AND status = $2
`

type CountEmailLogsByStatusParams struct {
	ProjectID uuid.UUID
	Status    string
}

func (q *Queries) CountEmailLogsByStatus(ctx context.Context, arg CountEmailLogsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailLogsByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailLog = `-- name: CreateEmailLog :one
INSERT INTO email_logs (project_id, subscriber_id, template_id, to_email, subject, status, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, subscriber_id, template_id, to_email, subject, status, error, sent_at
`

type CreateEmailLogParams struct {
	ProjectID    uuid.UUID
	SubscriberID uuid.NullUUID
	TemplateID   uuid.NullUUID
	ToEmail      string
	Subject      string
	Status       string
	Error        sql.NullString
}

func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, createEmailLog,
		arg.ProjectID,
		arg.SubscriberID,
		arg.TemplateID,
		arg.ToEmail,
		arg.Subject,
		arg.Status,
		arg.Error,
	)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriberID,
		&i.TemplateID,
		&i.ToEmail,
		&i.Subject,
		&i.Status,
		&i.Error,
		&i.SentAt,
	)
	return i, err
}

const listEmailLogsByProject = `-- name: ListEmailLogsByProject :many
SELECT id, project_id, subscriber_id, template_id, to_email, subject, status, error, sent_at FROM email_logs
WHERE project_id = $1
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type ListEmailLogsByProjectParams struct {
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListEmailLogsByProject(ctx context.Context, arg ListEmailLogsByProjectParams) ([]EmailLog, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLogsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLog
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriberID,
			&i.TemplateID,
			&i.ToEmail,
			&i.Subject,
			&i.Status,
			&i.Error,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
