// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_logs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countEmailLogsByProject = `-- name: CountEmailLogsByProject :one
SELECT COUNT(*) FROM email_logs WHERE project_id = $1
`

func (q *Queries) CountEmailLogsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailLogsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailLogsByProjectFiltered = `-- name: CountEmailLogsByProjectFiltered :one
SELECT COUNT(*) FROM email_logs
WHERE project_id = $1
AND ($2::text = '' OR status = $2::text)
AND ($3::timestamptz = '0001-01-01'::timestamptz OR sent_at >= $3)
AND ($4::timestamptz = '0001-01-01'::timestamptz OR sent_at <= $4)
AND ($5::text = '' OR to_email ILIKE '%' || $5::text || '%' OR subject ILIKE '%' || $5::text || '%')
AND ($6::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR template_id = $6::uuid)
AND ($7::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR newsletter_id = $7::uuid)
`

type CountEmailLogsByProjectFilteredParams struct {
	ProjectID uuid.UUID
	Column2   string
	Column3   time.Time
	Column4   time.Time
	Column5   string
	Column6   uuid.UUID
	Column7   uuid.UUID
}

func (q *Queries) CountEmailLogsByProjectFiltered(ctx context.Context, arg CountEmailLogsByProjectFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailLogsByProjectFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailLogsByStatus = `-- name: CountEmailLogsByStatus :one
SELECT COUNT(*) FROM email_logs WHERE project_id = $1 AND status = $2
`

type CountEmailLogsByStatusParams struct {
	ProjectID uuid.UUID
	Status    string
}

func (q *Queries) CountEmailLogsByStatus(ctx context.Context, arg CountEmailLogsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailLogsByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailLogsClicked = `-- name: CountEmailLogsClicked :one
SELECT COUNT(*) FROM email_logs WHERE project_id = $1 AND clicked_at IS NOT NULL
`

func (q *Queries) CountEmailLogsClicked(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailLogsClicked, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailLogsOpened = `-- name: CountEmailLogsOpened :one
SELECT COUNT(*) FROM email_logs WHERE project_id = $1 AND opened_at IS NOT NULL
`

func (q *Queries) CountEmailLogsOpened(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailLogsOpened, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailClick = `-- name: CreateEmailClick :exec
INSERT INTO email_clicks (log_id, url, url_hash, user_agent, ip_address)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEmailClickParams struct {
	LogID     uuid.UUID
	Url       string
	UrlHash   string
	UserAgent sql.NullString
	IpAddress pqtype.Inet
}

func (q *Queries) CreateEmailClick(ctx context.Context, arg CreateEmailClickParams) error {
	_, err := q.db.ExecContext(ctx, createEmailClick,
		arg.LogID,
		arg.Url,
		arg.UrlHash,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const createEmailLog = `-- name: CreateEmailLog :one
INSERT INTO email_logs (project_id, subscriber_id, template_id, to_email, subject, status, error, broadcast_id, newsletter_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, subscriber_id, template_id, to_email, subject, status, error, sent_at, opened_at, clicked_at, broadcast_id, complained_at, newsletter_id
`

type CreateEmailLogParams struct {
	ProjectID    uuid.UUID
	SubscriberID uuid.NullUUID
	TemplateID   uuid.NullUUID
	ToEmail      string
	Subject      string
	Status       string
	Error        sql.NullString
	BroadcastID  uuid.NullUUID
	NewsletterID uuid.NullUUID
}

func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, createEmailLog,
		arg.ProjectID,
		arg.SubscriberID,
		arg.TemplateID,
		arg.ToEmail,
		arg.Subject,
		arg.Status,
		arg.Error,
		arg.BroadcastID,
		arg.NewsletterID,
	)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriberID,
		&i.TemplateID,
		&i.ToEmail,
		&i.Subject,
		&i.Status,
		&i.Error,
		&i.SentAt,
		&i.OpenedAt,
		&i.ClickedAt,
		&i.BroadcastID,
		&i.ComplainedAt,
		&i.NewsletterID,
	)
	return i, err
}

const getEmailLog = `-- name: GetEmailLog :one
SELECT id, project_id, subscriber_id, template_id, to_email, subject, status, error, sent_at, opened_at, clicked_at, broadcast_id, complained_at, newsletter_id FROM email_logs WHERE id = $1 AND project_id = $2
`

type GetEmailLogParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetEmailLog(ctx context.Context, arg GetEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, getEmailLog, arg.ID, arg.ProjectID)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriberID,
		&i.TemplateID,
		&i.ToEmail,
		&i.Subject,
		&i.Status,
		&i.Error,
		&i.SentAt,
		&i.OpenedAt,
		&i.ClickedAt,
		&i.BroadcastID,
		&i.ComplainedAt,
		&i.NewsletterID,
	)
	return i, err
}

const getEmailLogProjectID = `-- name: GetEmailLogProjectID :one
SELECT project_id FROM email_logs WHERE id = $1
`

func (q *Queries) GetEmailLogProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getEmailLogProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listEmailClicksByLog = `-- name: ListEmailClicksByLog :many
SELECT id, log_id, url, clicked_at, user_agent
FROM email_clicks
WHERE log_id = $1
ORDER BY clicked_at ASC
`

type ListEmailClicksByLogRow struct {
	ID        uuid.UUID
	LogID     uuid.UUID
	Url       string
	ClickedAt time.Time
	UserAgent sql.NullString
}

func (q *Queries) ListEmailClicksByLog(ctx context.Context, logID uuid.UUID) ([]ListEmailClicksByLogRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailClicksByLog, logID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailClicksByLogRow
	for rows.Next() {
		var i ListEmailClicksByLogRow
		if err := rows.Scan(
			&i.ID,
			&i.LogID,
			&i.Url,
			&i.ClickedAt,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailLogsByProject = `-- name: ListEmailLogsByProject :many
SELECT id, project_id, subscriber_id, template_id, to_email, subject, status, error, sent_at, opened_at, clicked_at, broadcast_id, complained_at, newsletter_id FROM email_logs
WHERE project_id = $1
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type ListEmailLogsByProjectParams struct {
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListEmailLogsByProject(ctx context.Context, arg ListEmailLogsByProjectParams) ([]EmailLog, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLogsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLog
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriberID,
			&i.TemplateID,
			&i.ToEmail,
			&i.Subject,
			&i.Status,
			&i.Error,
			&i.SentAt,
			&i.OpenedAt,
			&i.ClickedAt,
			&i.BroadcastID,
			&i.ComplainedAt,
			&i.NewsletterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailLogsByProjectExport = `-- name: ListEmailLogsByProjectExport :many
SELECT id, project_id, subscriber_id, template_id, to_email, subject, status, error, sent_at, opened_at, clicked_at, broadcast_id, complained_at, newsletter_id FROM email_logs
WHERE project_id = $1
AND ($2::text = '' OR status = $2::text)
AND ($3::timestamptz = '0001-01-01'::timestamptz OR sent_at >= $3)
AND ($4::timestamptz = '0001-01-01'::timestamptz OR sent_at <= $4)
AND ($5::text = '' OR to_email ILIKE '%' || $5::text || '%' OR subject ILIKE '%' || $5::text || '%')
AND ($6::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR template_id = $6::uuid)
AND ($7::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR newsletter_id = $7::uuid)
ORDER BY sent_at DESC
`

type ListEmailLogsByProjectExportParams struct {
	ProjectID uuid.UUID
	Column2   string
	Column3   time.Time
	Column4   time.Time
	Column5   string
	Column6   uuid.UUID
	Column7   uuid.UUID
}

func (q *Queries) ListEmailLogsByProjectExport(ctx context.Context, arg ListEmailLogsByProjectExportParams) ([]EmailLog, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLogsByProjectExport,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLog
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriberID,
			&i.TemplateID,
			&i.ToEmail,
			&i.Subject,
			&i.Status,
			&i.Error,
			&i.SentAt,
			&i.OpenedAt,
			&i.ClickedAt,
			&i.BroadcastID,
			&i.ComplainedAt,
			&i.NewsletterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailLogsByProjectFiltered = `-- name: ListEmailLogsByProjectFiltered :many
SELECT id, project_id, subscriber_id, template_id, to_email, subject, status, error, sent_at, opened_at, clicked_at, broadcast_id, complained_at, newsletter_id FROM email_logs
WHERE project_id = $1
AND ($4::text = '' OR status = $4::text)
AND ($5::timestamptz = '0001-01-01'::timestamptz OR sent_at >= $5)
AND ($6::timestamptz = '0001-01-01'::timestamptz OR sent_at <= $6)
AND ($7::text = '' OR to_email ILIKE '%' || $7::text || '%' OR subject ILIKE '%' || $7::text || '%')
AND ($8::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR template_id = $8::uuid)
AND ($9::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR newsletter_id = $9::uuid)
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type ListEmailLogsByProjectFilteredParams struct {
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
	Column4   string
	Column5   time.Time
	Column6   time.Time
	Column7   string
	Column8   uuid.UUID
	Column9   uuid.UUID
}

func (q *Queries) ListEmailLogsByProjectFiltered(ctx context.Context, arg ListEmailLogsByProjectFilteredParams) ([]EmailLog, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLogsByProjectFiltered,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLog
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriberID,
			&i.TemplateID,
			&i.ToEmail,
			&i.Subject,
			&i.Status,
			&i.Error,
			&i.SentAt,
			&i.OpenedAt,
			&i.ClickedAt,
			&i.BroadcastID,
			&i.ComplainedAt,
			&i.NewsletterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailClicked = `-- name: MarkEmailClicked :execrows
UPDATE email_logs SET clicked_at = NOW() WHERE id = $1 AND clicked_at IS NULL
`

func (q *Queries) MarkEmailClicked(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailClicked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEmailOpened = `-- name: MarkEmailOpened :execrows
UPDATE email_logs SET opened_at = NOW() WHERE id = $1 AND opened_at IS NULL
`

func (q *Queries) MarkEmailOpened(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailOpened, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markLatestLogBouncedByEmail = `-- name: MarkLatestLogBouncedByEmail :exec
UPDATE email_logs SET status = 'bounced', error = $3
WHERE id = (
    SELECT el.id FROM email_logs el
    WHERE el.project_id = $1 AND el.to_email = $2 AND el.status = 'sent'
    ORDER BY el.sent_at DESC
    LIMIT 1
)
`

type MarkLatestLogBouncedByEmailParams struct {
	ProjectID uuid.UUID
	ToEmail   string
	Error     sql.NullString
}

func (q *Queries) MarkLatestLogBouncedByEmail(ctx context.Context, arg MarkLatestLogBouncedByEmailParams) error {
	_, err := q.db.ExecContext(ctx, markLatestLogBouncedByEmail, arg.ProjectID, arg.ToEmail, arg.Error)
	return err
}

const markLatestLogComplainedByEmail = `-- name: MarkLatestLogComplainedByEmail :exec
UPDATE email_logs SET complained_at = NOW()
WHERE id = (
    SELECT el.id FROM email_logs el
    WHERE el.project_id = $1 AND el.to_email = $2 AND el.status = 'sent' AND el.complained_at IS NULL
    ORDER BY el.sent_at DESC
    LIMIT 1
)
`

type MarkLatestLogComplainedByEmailParams struct {
	ProjectID uuid.UUID
	ToEmail   string
}

func (q *Queries) MarkLatestLogComplainedByEmail(ctx context.Context, arg MarkLatestLogComplainedByEmailParams) error {
	_, err := q.db.ExecContext(ctx, markLatestLogComplainedByEmail, arg.ProjectID, arg.ToEmail)
	return err
}

const updateEmailLogStatus = `-- name: UpdateEmailLogStatus :exec
UPDATE email_logs SET status = $2, error = $3 WHERE id = $1
`

type UpdateEmailLogStatusParams struct {
	ID     uuid.UUID
	Status string
	Error  sql.NullString
}

func (q *Queries) UpdateEmailLogStatus(ctx context.Context, arg UpdateEmailLogStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailLogStatus, arg.ID, arg.Status, arg.Error)
	return err
}
