// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: field_definitions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createFieldDefinition = `-- name: CreateFieldDefinition :one
INSERT INTO subscriber_field_definitions (project_id, key, label, field_type, options, required)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, key, label, field_type, options, required, created_at
`

type CreateFieldDefinitionParams struct {
	ProjectID uuid.UUID
	Key       string
	Label     string
	FieldType string
	Options   pqtype.NullRawMessage
	Required  bool
}

func (q *Queries) CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) (SubscriberFieldDefinition, error) {
	row := q.db.QueryRowContext(ctx, createFieldDefinition,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.FieldType,
		arg.Options,
		arg.Required,
	)
	var i SubscriberFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.FieldType,
		&i.Options,
		&i.Required,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFieldDefinition = `-- name: DeleteFieldDefinition :exec
DELETE FROM subscriber_field_definitions
WHERE id = $1 AND project_id = $2
`

type DeleteFieldDefinitionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteFieldDefinition(ctx context.Context, arg DeleteFieldDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, deleteFieldDefinition, arg.ID, arg.ProjectID)
	return err
}

const getFieldDefinition = `-- name: GetFieldDefinition :one
SELECT id, project_id, key, label, field_type, options, required, created_at FROM subscriber_field_definitions
WHERE id = $1 AND project_id = $2
`

type GetFieldDefinitionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetFieldDefinition(ctx context.Context, arg GetFieldDefinitionParams) (SubscriberFieldDefinition, error) {
	row := q.db.QueryRowContext(ctx, getFieldDefinition, arg.ID, arg.ProjectID)
	var i SubscriberFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.FieldType,
		&i.Options,
		&i.Required,
		&i.CreatedAt,
	)
	return i, err
}

const listFieldDefinitionsByProject = `-- name: ListFieldDefinitionsByProject :many
SELECT id, project_id, key, label, field_type, options, required, created_at FROM subscriber_field_definitions
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListFieldDefinitionsByProject(ctx context.Context, projectID uuid.UUID) ([]SubscriberFieldDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listFieldDefinitionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriberFieldDefinition
	for rows.Next() {
		var i SubscriberFieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.FieldType,
			&i.Options,
			&i.Required,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFieldDefinition = `-- name: UpdateFieldDefinition :one
UPDATE subscriber_field_definitions SET
    label = $3,
    options = $4,
    required = $5
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, key, label, field_type, options, required, created_at
`

type UpdateFieldDefinitionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Label     string
	Options   pqtype.NullRawMessage
	Required  bool
}

func (q *Queries) UpdateFieldDefinition(ctx context.Context, arg UpdateFieldDefinitionParams) (SubscriberFieldDefinition, error) {
	row := q.db.QueryRowContext(ctx, updateFieldDefinition,
		arg.ID,
		arg.ProjectID,
		arg.Label,
		arg.Options,
		arg.Required,
	)
	var i SubscriberFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.FieldType,
		&i.Options,
		&i.Required,
		&i.CreatedAt,
	)
	return i, err
}
