// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_settings.sql

package db

import (
	"context"
)

const ensureInstanceSettingsRow = `-- name: EnsureInstanceSettingsRow :exec
INSERT INTO instance_settings (id) VALUES (true)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureInstanceSettingsRow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureInstanceSettingsRow)
	return err
}

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, public_url, session_idle_timeout_minutes, updated_at, license_key_encrypted FROM instance_settings WHERE id = true
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.SessionIdleTimeoutMinutes,
		&i.UpdatedAt,
		&i.LicenseKeyEncrypted,
	)
	return i, err
}

const setInstanceLicenseKey = `-- name: SetInstanceLicenseKey :one
UPDATE instance_settings SET
    license_key_encrypted = $1,
    updated_at = NOW()
WHERE id = true
RETURNING id, public_url, session_idle_timeout_minutes, updated_at, license_key_encrypted
`

func (q *Queries) SetInstanceLicenseKey(ctx context.Context, licenseKeyEncrypted string) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, setInstanceLicenseKey, licenseKeyEncrypted)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.SessionIdleTimeoutMinutes,
		&i.UpdatedAt,
		&i.LicenseKeyEncrypted,
	)
	return i, err
}

const setInstancePublicURL = `-- name: SetInstancePublicURL :one
UPDATE instance_settings SET
    public_url = $1,
    updated_at = NOW()
WHERE id = true
RETURNING id, public_url, session_idle_timeout_minutes, updated_at, license_key_encrypted
`

func (q *Queries) SetInstancePublicURL(ctx context.Context, publicUrl string) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, setInstancePublicURL, publicUrl)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.SessionIdleTimeoutMinutes,
		&i.UpdatedAt,
		&i.LicenseKeyEncrypted,
	)
	return i, err
}

const updateInstanceSettings = `-- name: UpdateInstanceSettings :one
UPDATE instance_settings SET
    public_url = $1,
    session_idle_timeout_minutes = $2,
    updated_at = NOW()
WHERE id = true
RETURNING id, public_url, session_idle_timeout_minutes, updated_at, license_key_encrypted
`

type UpdateInstanceSettingsParams struct {
	PublicUrl                 string
	SessionIdleTimeoutMinutes int32
}

func (q *Queries) UpdateInstanceSettings(ctx context.Context, arg UpdateInstanceSettingsParams) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceSettings, arg.PublicUrl, arg.SessionIdleTimeoutMinutes)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.SessionIdleTimeoutMinutes,
		&i.UpdatedAt,
		&i.LicenseKeyEncrypted,
	)
	return i, err
}
