// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_settings.sql

package db

import (
	"context"
)

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, public_url, session_idle_timeout_minutes, updated_at FROM instance_settings WHERE id = true
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.SessionIdleTimeoutMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const setInstancePublicURL = `-- name: SetInstancePublicURL :one
UPDATE instance_settings SET
    public_url = $1,
    updated_at = NOW()
WHERE id = true
RETURNING id, public_url, session_idle_timeout_minutes, updated_at
`

func (q *Queries) SetInstancePublicURL(ctx context.Context, publicUrl string) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, setInstancePublicURL, publicUrl)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.SessionIdleTimeoutMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceSettings = `-- name: UpdateInstanceSettings :one
UPDATE instance_settings SET
    public_url = $1,
    session_idle_timeout_minutes = $2,
    updated_at = NOW()
WHERE id = true
RETURNING id, public_url, session_idle_timeout_minutes, updated_at
`

type UpdateInstanceSettingsParams struct {
	PublicUrl                 string
	SessionIdleTimeoutMinutes int32
}

func (q *Queries) UpdateInstanceSettings(ctx context.Context, arg UpdateInstanceSettingsParams) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceSettings, arg.PublicUrl, arg.SessionIdleTimeoutMinutes)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.SessionIdleTimeoutMinutes,
		&i.UpdatedAt,
	)
	return i, err
}
