// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	Name       string
	KeyHash    string
	KeyPrefix  string
	LastUsedAt sql.NullTime
	CreatedAt  time.Time
}

type Campaign struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	TemplateID  uuid.UUID
	Name        string
	Status      string
	ScheduledAt time.Time
	SentAt      sql.NullTime
	SentCount   int32
	FailedCount int32
	CreatedAt   time.Time
}

type EmailLog struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	SubscriberID uuid.NullUUID
	TemplateID   uuid.NullUUID
	ToEmail      string
	Subject      string
	Status       string
	Error        sql.NullString
	SentAt       time.Time
	OpenedAt     sql.NullTime
}

type Project struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Name                  string
	FromName              sql.NullString
	FromEmail             sql.NullString
	SmtpHost              sql.NullString
	SmtpPort              sql.NullInt32
	SmtpUser              sql.NullString
	SmtpPasswordEncrypted sql.NullString
	WebhookUrl            sql.NullString
	WebhookSecret         sql.NullString
	TrackingEnabled       bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Description           sql.NullString
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Subscriber struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Email          string
	Name           string
	Status         string
	Metadata       json.RawMessage
	SubscribedAt   time.Time
	UnsubscribedAt sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Template struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Subject   string
	HtmlBody  string
	TextBody  string
	Variables json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Email              string
	PasswordHash       sql.NullString
	Name               string
	Plan               string
	MonthlyEmailLimit  int32
	MonthlyEmailsSent  int32
	MonthlyResetAt     time.Time
	Provider           sql.NullString
	ProviderID         sql.NullString
	IsVerified         bool
	IsBanned           bool
	BanReason          sql.NullString
	CustomerID         sql.NullString
	SubscriptionID     sql.NullString
	SubscriptionStatus sql.NullString
	PlanChangedAt      sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
