// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Project struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Name                  string
	FromName              string
	FromEmail             string
	SmtpHost              sql.NullString
	SmtpPort              sql.NullInt32
	SmtpUser              sql.NullString
	SmtpPasswordEncrypted sql.NullString
	WebhookUrl            sql.NullString
	WebhookSecret         sql.NullString
	TrackingEnabled       bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Email              string
	PasswordHash       sql.NullString
	Name               string
	Plan               string
	MonthlyEmailLimit  int32
	MonthlyEmailsSent  int32
	MonthlyResetAt     time.Time
	Provider           sql.NullString
	ProviderID         sql.NullString
	IsVerified         bool
	IsBanned           bool
	BanReason          sql.NullString
	CustomerID         sql.NullString
	SubscriptionID     sql.NullString
	SubscriptionStatus sql.NullString
	PlanChangedAt      sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
