// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiKey struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	Name       string
	KeyHash    string
	KeyPrefix  string
	LastUsedAt sql.NullTime
	CreatedAt  time.Time
}

type AuditLog struct {
	ID         uuid.UUID
	ProjectID  uuid.NullUUID
	UserID     uuid.NullUUID
	Action     string
	TargetType sql.NullString
	TargetID   sql.NullString
	Metadata   json.RawMessage
	IpAddress  pqtype.Inet
	UserAgent  sql.NullString
	CreatedAt  time.Time
}

type Broadcast struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	TemplateID      uuid.UUID
	Subject         string
	Variables       json.RawMessage
	Status          string
	TotalRecipients int32
	SentCount       int32
	FailedCount     int32
	SuppressedCount int32
	StartedAt       time.Time
	FinishedAt      sql.NullTime
}

type BroadcastJob struct {
	ID             uuid.UUID
	BroadcastID    uuid.UUID
	ProjectID      uuid.UUID
	SubscriberID   uuid.UUID
	RecipientEmail string
	Status         string
	Attempts       int32
	LastError      sql.NullString
	ScheduledAt    time.Time
	CompletedAt    sql.NullTime
	CreatedAt      time.Time
}

type Campaign struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	TemplateID  uuid.UUID
	Name        string
	Status      string
	ScheduledAt time.Time
	SentAt      sql.NullTime
	SentCount   int32
	FailedCount int32
	CreatedAt   time.Time
	Variables   json.RawMessage
	Subject     string
	BroadcastID uuid.NullUUID
}

type EmailClick struct {
	ID        uuid.UUID
	LogID     uuid.UUID
	Url       string
	UrlHash   string
	ClickedAt time.Time
	UserAgent sql.NullString
	IpAddress pqtype.Inet
}

type EmailLog struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	SubscriberID uuid.NullUUID
	TemplateID   uuid.NullUUID
	ToEmail      string
	Subject      string
	Status       string
	Error        sql.NullString
	SentAt       time.Time
	OpenedAt     sql.NullTime
	ClickedAt    sql.NullTime
}

type Project struct {
	ID                          uuid.UUID
	UserID                      uuid.UUID
	Name                        string
	FromName                    sql.NullString
	FromEmail                   sql.NullString
	SmtpHost                    sql.NullString
	SmtpPort                    sql.NullInt32
	SmtpUser                    sql.NullString
	SmtpPasswordEncrypted       sql.NullString
	WebhookUrl                  sql.NullString
	WebhookSecret               sql.NullString
	TrackingEnabled             bool
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	Description                 sql.NullString
	BounceToken                 uuid.UUID
	BounceImapHost              sql.NullString
	BounceImapPort              sql.NullInt32
	BounceImapUser              sql.NullString
	BounceImapPasswordEncrypted sql.NullString
	BounceImapFolder            string
	BounceImapEnabled           bool
	WorkspaceID                 uuid.UUID
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Segment struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Predicate json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Subscriber struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Email          string
	Name           string
	Status         string
	Metadata       json.RawMessage
	SubscribedAt   time.Time
	UnsubscribedAt sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Tags           []string
}

type SubscriberFieldDefinition struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Key       string
	Label     string
	FieldType string
	Options   pqtype.NullRawMessage
	Required  bool
	CreatedAt time.Time
}

type Suppression struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	EmailNormalized string
	Reason          string
	Source          sql.NullString
	CreatedAt       time.Time
	LastSeenAt      time.Time
}

type Template struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Subject   string
	HtmlBody  string
	TextBody  string
	Variables json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Email              string
	PasswordHash       sql.NullString
	Name               string
	Plan               string
	MonthlyEmailLimit  int32
	MonthlyEmailsSent  int32
	MonthlyResetAt     time.Time
	Provider           sql.NullString
	ProviderID         sql.NullString
	IsVerified         bool
	IsBanned           bool
	BanReason          sql.NullString
	CustomerID         sql.NullString
	SubscriptionID     sql.NullString
	SubscriptionStatus sql.NullString
	PlanChangedAt      sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
	TotpSecret         sql.NullString
	TotpEnabled        bool
	TotpVerifiedAt     sql.NullTime
	EmailVerified      bool
}

type UserRecoveryCode struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CodeHash  string
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Webhook struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Url       string
	Secret    string
	Events    []string
	Active    bool
	CreatedAt time.Time
}

type WebhookDelivery struct {
	ID             uuid.UUID
	WebhookID      uuid.UUID
	EventType      string
	Payload        json.RawMessage
	Status         string
	Attempts       int32
	LastStatusCode sql.NullInt32
	LastError      sql.NullString
	NextAttemptAt  time.Time
	DeliveredAt    sql.NullTime
	CreatedAt      time.Time
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	InvitedBy   uuid.NullUUID
	CreatedAt   time.Time
}
