// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletters.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addNewsletterSubscription = `-- name: AddNewsletterSubscription :exec
INSERT INTO newsletter_subscriptions (newsletter_id, subscriber_id, project_id)
SELECT n.id, $1::uuid, n.project_id
FROM newsletters n
WHERE n.id = $2::uuid AND n.project_id = $3::uuid
ON CONFLICT (newsletter_id, subscriber_id) DO UPDATE SET unsubscribed_at = NULL
`

type AddNewsletterSubscriptionParams struct {
	SubscriberID uuid.UUID
	NewsletterID uuid.UUID
	ProjectID    uuid.UUID
}

func (q *Queries) AddNewsletterSubscription(ctx context.Context, arg AddNewsletterSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, addNewsletterSubscription, arg.SubscriberID, arg.NewsletterID, arg.ProjectID)
	return err
}

const bulkAddNewsletterSubscriptions = `-- name: BulkAddNewsletterSubscriptions :exec
INSERT INTO newsletter_subscriptions (newsletter_id, subscriber_id, project_id)
SELECT n.id, s.id, n.project_id
FROM newsletters n
CROSS JOIN subscribers s
WHERE n.id = $1::uuid
  AND n.project_id = $2::uuid
  AND s.project_id = $2::uuid
  AND s.id = ANY($3::uuid[])
ON CONFLICT (newsletter_id, subscriber_id) DO UPDATE SET unsubscribed_at = NULL
`

type BulkAddNewsletterSubscriptionsParams struct {
	NewsletterID  uuid.UUID
	ProjectID     uuid.UUID
	SubscriberIds []uuid.UUID
}

func (q *Queries) BulkAddNewsletterSubscriptions(ctx context.Context, arg BulkAddNewsletterSubscriptionsParams) error {
	_, err := q.db.ExecContext(ctx, bulkAddNewsletterSubscriptions, arg.NewsletterID, arg.ProjectID, pq.Array(arg.SubscriberIds))
	return err
}

const bulkRemoveNewsletterSubscriptions = `-- name: BulkRemoveNewsletterSubscriptions :exec
DELETE FROM newsletter_subscriptions
WHERE newsletter_id = $1::uuid
  AND project_id = $2::uuid
  AND subscriber_id = ANY($3::uuid[])
`

type BulkRemoveNewsletterSubscriptionsParams struct {
	NewsletterID  uuid.UUID
	ProjectID     uuid.UUID
	SubscriberIds []uuid.UUID
}

func (q *Queries) BulkRemoveNewsletterSubscriptions(ctx context.Context, arg BulkRemoveNewsletterSubscriptionsParams) error {
	_, err := q.db.ExecContext(ctx, bulkRemoveNewsletterSubscriptions, arg.NewsletterID, arg.ProjectID, pq.Array(arg.SubscriberIds))
	return err
}

const createNewsletter = `-- name: CreateNewsletter :one
INSERT INTO newsletters (project_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, description, created_at, updated_at
`

type CreateNewsletterParams struct {
	ProjectID   uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateNewsletter(ctx context.Context, arg CreateNewsletterParams) (Newsletter, error) {
	row := q.db.QueryRowContext(ctx, createNewsletter, arg.ProjectID, arg.Name, arg.Description)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNewsletter = `-- name: DeleteNewsletter :exec
DELETE FROM newsletters
WHERE id = $1 AND project_id = $2
`

type DeleteNewsletterParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteNewsletter(ctx context.Context, arg DeleteNewsletterParams) error {
	_, err := q.db.ExecContext(ctx, deleteNewsletter, arg.ID, arg.ProjectID)
	return err
}

const deleteSubscriberNewsletterSubscriptions = `-- name: DeleteSubscriberNewsletterSubscriptions :exec
DELETE FROM newsletter_subscriptions
WHERE subscriber_id = $1 AND project_id = $2
`

type DeleteSubscriberNewsletterSubscriptionsParams struct {
	SubscriberID uuid.UUID
	ProjectID    uuid.UUID
}

func (q *Queries) DeleteSubscriberNewsletterSubscriptions(ctx context.Context, arg DeleteSubscriberNewsletterSubscriptionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriberNewsletterSubscriptions, arg.SubscriberID, arg.ProjectID)
	return err
}

const getNewsletterByID = `-- name: GetNewsletterByID :one
SELECT id, project_id, name, description, created_at, updated_at FROM newsletters
WHERE id = $1 AND project_id = $2
`

type GetNewsletterByIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetNewsletterByID(ctx context.Context, arg GetNewsletterByIDParams) (Newsletter, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterByID, arg.ID, arg.ProjectID)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveNewsletterSubscribers = `-- name: ListActiveNewsletterSubscribers :many
SELECT s.id, s.email FROM subscribers s
JOIN newsletter_subscriptions ns ON ns.subscriber_id = s.id
WHERE ns.newsletter_id = $1
  AND s.project_id = $2
  AND s.status = 'active'
  AND ns.unsubscribed_at IS NULL
ORDER BY s.created_at DESC
`

type ListActiveNewsletterSubscribersParams struct {
	NewsletterID uuid.UUID
	ProjectID    uuid.UUID
}

type ListActiveNewsletterSubscribersRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) ListActiveNewsletterSubscribers(ctx context.Context, arg ListActiveNewsletterSubscribersParams) ([]ListActiveNewsletterSubscribersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNewsletterSubscribers, arg.NewsletterID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNewsletterSubscribersRow
	for rows.Next() {
		var i ListActiveNewsletterSubscribersRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewslettersByProject = `-- name: ListNewslettersByProject :many
SELECT n.id, n.project_id, n.name, n.description, n.created_at, n.updated_at,
    (SELECT COUNT(*) FROM newsletter_subscriptions ns
       JOIN subscribers s ON s.id = ns.subscriber_id
      WHERE ns.newsletter_id = n.id
        AND ns.unsubscribed_at IS NULL
        AND s.status = 'active') AS active_count
FROM newsletters n
WHERE n.project_id = $1
ORDER BY n.created_at DESC
`

type ListNewslettersByProjectRow struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ActiveCount int64
}

func (q *Queries) ListNewslettersByProject(ctx context.Context, projectID uuid.UUID) ([]ListNewslettersByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listNewslettersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewslettersByProjectRow
	for rows.Next() {
		var i ListNewslettersByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriberNewsletters = `-- name: ListSubscriberNewsletters :many
SELECT n.id, n.name, ns.unsubscribed_at FROM newsletters n
JOIN newsletter_subscriptions ns ON ns.newsletter_id = n.id
WHERE ns.subscriber_id = $1 AND n.project_id = $2
ORDER BY n.created_at DESC
`

type ListSubscriberNewslettersParams struct {
	SubscriberID uuid.UUID
	ProjectID    uuid.UUID
}

type ListSubscriberNewslettersRow struct {
	ID             uuid.UUID
	Name           string
	UnsubscribedAt sql.NullTime
}

func (q *Queries) ListSubscriberNewsletters(ctx context.Context, arg ListSubscriberNewslettersParams) ([]ListSubscriberNewslettersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriberNewsletters, arg.SubscriberID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriberNewslettersRow
	for rows.Next() {
		var i ListSubscriberNewslettersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.UnsubscribedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNewsletterUnsubscribed = `-- name: MarkNewsletterUnsubscribed :exec
INSERT INTO newsletter_subscriptions (newsletter_id, subscriber_id, project_id, unsubscribed_at)
SELECT n.id, $1::uuid, n.project_id, NOW()
FROM newsletters n
WHERE n.id = $2::uuid AND n.project_id = $3::uuid
ON CONFLICT (newsletter_id, subscriber_id) DO UPDATE SET unsubscribed_at = NOW()
`

type MarkNewsletterUnsubscribedParams struct {
	SubscriberID uuid.UUID
	NewsletterID uuid.UUID
	ProjectID    uuid.UUID
}

func (q *Queries) MarkNewsletterUnsubscribed(ctx context.Context, arg MarkNewsletterUnsubscribedParams) error {
	_, err := q.db.ExecContext(ctx, markNewsletterUnsubscribed, arg.SubscriberID, arg.NewsletterID, arg.ProjectID)
	return err
}

const updateNewsletter = `-- name: UpdateNewsletter :one
UPDATE newsletters SET
    name = $3,
    description = $4,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, description, created_at, updated_at
`

type UpdateNewsletterParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateNewsletter(ctx context.Context, arg UpdateNewsletterParams) (Newsletter, error) {
	row := q.db.QueryRowContext(ctx, updateNewsletter,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
	)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
