// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO user_recovery_codes (user_id, code_hash)
VALUES ($1, $2)
`

type CreateRecoveryCodeParams struct {
	UserID   uuid.UUID
	CodeHash string
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteUserRecoveryCodes = `-- name: DeleteUserRecoveryCodes :exec
DELETE FROM user_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteUserRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserRecoveryCodes, userID)
	return err
}

const listUserRecoveryCodes = `-- name: ListUserRecoveryCodes :many
SELECT id, user_id, code_hash, used_at, created_at
FROM user_recovery_codes
WHERE user_id = $1 AND used_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListUserRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]UserRecoveryCode, error) {
	rows, err := q.db.QueryContext(ctx, listUserRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRecoveryCode
	for rows.Next() {
		var i UserRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE user_recovery_codes SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markRecoveryCodeUsed, id)
	return err
}
