// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (project_id, name, predicate)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, predicate, created_at, updated_at
`

type CreateSegmentParams struct {
	ProjectID uuid.UUID
	Name      string
	Predicate json.RawMessage
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRowContext(ctx, createSegment, arg.ProjectID, arg.Name, arg.Predicate)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSegment = `-- name: DeleteSegment :exec
DELETE FROM segments
WHERE id = $1 AND project_id = $2
`

type DeleteSegmentParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteSegment(ctx context.Context, arg DeleteSegmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteSegment, arg.ID, arg.ProjectID)
	return err
}

const getSegment = `-- name: GetSegment :one
SELECT id, project_id, name, predicate, created_at, updated_at FROM segments
WHERE id = $1 AND project_id = $2
`

type GetSegmentParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetSegment(ctx context.Context, arg GetSegmentParams) (Segment, error) {
	row := q.db.QueryRowContext(ctx, getSegment, arg.ID, arg.ProjectID)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSegmentsByProject = `-- name: ListSegmentsByProject :many
SELECT id, project_id, name, predicate, created_at, updated_at FROM segments
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSegmentsByProject(ctx context.Context, projectID uuid.UUID) ([]Segment, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Predicate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegment = `-- name: UpdateSegment :one
UPDATE segments SET
    name = $3,
    predicate = $4,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, predicate, created_at, updated_at
`

type UpdateSegmentParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Predicate json.RawMessage
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) (Segment, error) {
	row := q.db.QueryRowContext(ctx, updateSegment,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Predicate,
	)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Predicate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
