// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkAddSubscriberTags = `-- name: BulkAddSubscriberTags :exec
UPDATE subscribers SET
    tags = ARRAY(SELECT DISTINCT unnest(tags || $3::text[])),
    updated_at = NOW()
WHERE project_id = $1 AND id = ANY($2::uuid[])
`

type BulkAddSubscriberTagsParams struct {
	ProjectID uuid.UUID
	Column2   []uuid.UUID
	Column3   []string
}

func (q *Queries) BulkAddSubscriberTags(ctx context.Context, arg BulkAddSubscriberTagsParams) error {
	_, err := q.db.ExecContext(ctx, bulkAddSubscriberTags, arg.ProjectID, pq.Array(arg.Column2), pq.Array(arg.Column3))
	return err
}

const bulkDeleteSubscribers = `-- name: BulkDeleteSubscribers :exec
DELETE FROM subscribers 
WHERE project_id = $1 AND id = ANY($2::uuid[])
`

type BulkDeleteSubscribersParams struct {
	ProjectID uuid.UUID
	Column2   []uuid.UUID
}

func (q *Queries) BulkDeleteSubscribers(ctx context.Context, arg BulkDeleteSubscribersParams) error {
	_, err := q.db.ExecContext(ctx, bulkDeleteSubscribers, arg.ProjectID, pq.Array(arg.Column2))
	return err
}

const bulkRemoveSubscriberTags = `-- name: BulkRemoveSubscriberTags :exec
UPDATE subscribers SET
    tags = ARRAY(SELECT unnest(tags) EXCEPT SELECT unnest($3::text[])),
    updated_at = NOW()
WHERE project_id = $1 AND id = ANY($2::uuid[])
`

type BulkRemoveSubscriberTagsParams struct {
	ProjectID uuid.UUID
	Column2   []uuid.UUID
	Column3   []string
}

func (q *Queries) BulkRemoveSubscriberTags(ctx context.Context, arg BulkRemoveSubscriberTagsParams) error {
	_, err := q.db.ExecContext(ctx, bulkRemoveSubscriberTags, arg.ProjectID, pq.Array(arg.Column2), pq.Array(arg.Column3))
	return err
}

const bulkUpdateSubscriberStatus = `-- name: BulkUpdateSubscriberStatus :exec
UPDATE subscribers 
SET 
    status = $3,
    unsubscribed_at = CASE WHEN $3 = 'unsubscribed' THEN NOW() ELSE unsubscribed_at END,
    updated_at = NOW()
WHERE project_id = $1 AND id = ANY($2::uuid[])
`

type BulkUpdateSubscriberStatusParams struct {
	ProjectID uuid.UUID
	Column2   []uuid.UUID
	Status    string
}

func (q *Queries) BulkUpdateSubscriberStatus(ctx context.Context, arg BulkUpdateSubscriberStatusParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpdateSubscriberStatus, arg.ProjectID, pq.Array(arg.Column2), arg.Status)
	return err
}

const countActiveSubscribersByProject = `-- name: CountActiveSubscribersByProject :one
SELECT COUNT(*) FROM subscribers WHERE project_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveSubscribersByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSubscribersByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscribersByProject = `-- name: CountSubscribersByProject :one
SELECT COUNT(*) FROM subscribers s
WHERE s.project_id = $1
AND ($2::text = '' OR s.status = $2::text)
AND ($3::text = '' OR $3::text = ANY(s.tags))
AND ($4::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR s.id IN (
    SELECT ns.subscriber_id FROM newsletter_subscriptions ns
    WHERE ns.newsletter_id = $4::uuid AND ns.unsubscribed_at IS NULL))
`

type CountSubscribersByProjectParams struct {
	ProjectID uuid.UUID
	Column2   string
	Column3   string
	Column4   uuid.UUID
}

func (q *Queries) CountSubscribersByProject(ctx context.Context, arg CountSubscribersByProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscribersByProject,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (project_id, email, name, status, metadata, tags)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags
`

type CreateSubscriberParams struct {
	ProjectID uuid.UUID
	Email     string
	Name      string
	Status    string
	Metadata  json.RawMessage
	Tags      []string
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, createSubscriber,
		arg.ProjectID,
		arg.Email,
		arg.Name,
		arg.Status,
		arg.Metadata,
		pq.Array(arg.Tags),
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscribers WHERE id = $1 AND project_id = $2
`

type DeleteSubscriberParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteSubscriber(ctx context.Context, arg DeleteSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriber, arg.ID, arg.ProjectID)
	return err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags FROM subscribers WHERE email = $1 AND project_id = $2
`

type GetSubscriberByEmailParams struct {
	Email     string
	ProjectID uuid.UUID
}

func (q *Queries) GetSubscriberByEmail(ctx context.Context, arg GetSubscriberByEmailParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByEmail, arg.Email, arg.ProjectID)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags FROM subscribers WHERE id = $1 AND project_id = $2
`

type GetSubscriberByIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetSubscriberByID(ctx context.Context, arg GetSubscriberByIDParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByID, arg.ID, arg.ProjectID)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const listActiveSubscribersByProject = `-- name: ListActiveSubscribersByProject :many
SELECT id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags FROM subscribers
WHERE project_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSubscribersByProject(ctx context.Context, projectID uuid.UUID) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscribersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.Metadata,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctTagsByProject = `-- name: ListDistinctTagsByProject :many
SELECT DISTINCT unnest(tags)::text AS tag
FROM subscribers
WHERE project_id = $1
ORDER BY tag
`

func (q *Queries) ListDistinctTagsByProject(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctTagsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribersByProject = `-- name: ListSubscribersByProject :many
SELECT s.id, s.project_id, s.email, s.name, s.status, s.metadata, s.subscribed_at, s.unsubscribed_at, s.created_at, s.updated_at, s.tags FROM subscribers s
WHERE s.project_id = $1
AND ($4::text = '' OR s.status = $4::text)
AND ($5::text = '' OR $5::text = ANY(s.tags))
AND ($6::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR s.id IN (
    SELECT ns.subscriber_id FROM newsletter_subscriptions ns
    WHERE ns.newsletter_id = $6::uuid AND ns.unsubscribed_at IS NULL))
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSubscribersByProjectParams struct {
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
	Column4   string
	Column5   string
	Column6   uuid.UUID
}

func (q *Queries) ListSubscribersByProject(ctx context.Context, arg ListSubscribersByProjectParams) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listSubscribersByProject,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.Metadata,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubscriberTags = `-- name: SetSubscriberTags :one
UPDATE subscribers SET
    tags = $3,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags
`

type SetSubscriberTagsParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Tags      []string
}

func (q *Queries) SetSubscriberTags(ctx context.Context, arg SetSubscriberTagsParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, setSubscriberTags, arg.ID, arg.ProjectID, pq.Array(arg.Tags))
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const updateSubscriber = `-- name: UpdateSubscriber :one
UPDATE subscribers SET
    name = $3,
    email = $4,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags
`

type UpdateSubscriberParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Email     string
}

func (q *Queries) UpdateSubscriber(ctx context.Context, arg UpdateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriber,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Email,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const updateSubscriberMetadata = `-- name: UpdateSubscriberMetadata :one
UPDATE subscribers SET
    metadata = $3,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags
`

type UpdateSubscriberMetadataParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Metadata  json.RawMessage
}

func (q *Queries) UpdateSubscriberMetadata(ctx context.Context, arg UpdateSubscriberMetadataParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriberMetadata, arg.ID, arg.ProjectID, arg.Metadata)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const updateSubscriberStatus = `-- name: UpdateSubscriberStatus :one
UPDATE subscribers SET
    status = $3,
    unsubscribed_at = CASE WHEN $4 = 'unsubscribed' THEN NOW() ELSE unsubscribed_at END,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at, tags
`

type UpdateSubscriberStatusParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Status    string
	Column4   interface{}
}

func (q *Queries) UpdateSubscriberStatus(ctx context.Context, arg UpdateSubscriberStatusParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriberStatus,
		arg.ID,
		arg.ProjectID,
		arg.Status,
		arg.Column4,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}
