// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscribers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveSubscribersByProject = `-- name: CountActiveSubscribersByProject :one
SELECT COUNT(*) FROM subscribers WHERE project_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveSubscribersByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSubscribersByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscribersByProject = `-- name: CountSubscribersByProject :one
SELECT COUNT(*) FROM subscribers WHERE project_id = $1
`

func (q *Queries) CountSubscribersByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscribersByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (project_id, email, name, status)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at
`

type CreateSubscriberParams struct {
	ProjectID uuid.UUID
	Email     string
	Name      string
	Status    string
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, createSubscriber,
		arg.ProjectID,
		arg.Email,
		arg.Name,
		arg.Status,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscribers WHERE id = $1 AND project_id = $2
`

type DeleteSubscriberParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteSubscriber(ctx context.Context, arg DeleteSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriber, arg.ID, arg.ProjectID)
	return err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at FROM subscribers WHERE email = $1 AND project_id = $2
`

type GetSubscriberByEmailParams struct {
	Email     string
	ProjectID uuid.UUID
}

func (q *Queries) GetSubscriberByEmail(ctx context.Context, arg GetSubscriberByEmailParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByEmail, arg.Email, arg.ProjectID)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at FROM subscribers WHERE id = $1 AND project_id = $2
`

type GetSubscriberByIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetSubscriberByID(ctx context.Context, arg GetSubscriberByIDParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByID, arg.ID, arg.ProjectID)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSubscribersByProject = `-- name: ListActiveSubscribersByProject :many
SELECT id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at FROM subscribers
WHERE project_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSubscribersByProject(ctx context.Context, projectID uuid.UUID) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscribersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.Metadata,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribersByProject = `-- name: ListSubscribersByProject :many
SELECT id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at FROM subscribers
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSubscribersByProjectParams struct {
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListSubscribersByProject(ctx context.Context, arg ListSubscribersByProjectParams) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listSubscribersByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.Metadata,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriber = `-- name: UpdateSubscriber :one
UPDATE subscribers SET
    name = $3,
    email = $4,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at
`

type UpdateSubscriberParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Email     string
}

func (q *Queries) UpdateSubscriber(ctx context.Context, arg UpdateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriber,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Email,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriberStatus = `-- name: UpdateSubscriberStatus :one
UPDATE subscribers SET
    status = $3,
    unsubscribed_at = CASE WHEN $3::text = 'unsubscribed' THEN NOW() ELSE unsubscribed_at END,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, email, name, status, metadata, subscribed_at, unsubscribed_at, created_at, updated_at
`

type UpdateSubscriberStatusParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Status    string
}

func (q *Queries) UpdateSubscriberStatus(ctx context.Context, arg UpdateSubscriberStatusParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriberStatus, arg.ID, arg.ProjectID, arg.Status)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
