// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppressions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countSuppressionsByProject = `-- name: CountSuppressionsByProject :one
SELECT COUNT(*) FROM suppressions
WHERE project_id = $1
  AND ($2::text = '' OR reason = $2::text)
`

type CountSuppressionsByProjectParams struct {
	ProjectID uuid.UUID
	Column2   string
}

func (q *Queries) CountSuppressionsByProject(ctx context.Context, arg CountSuppressionsByProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSuppressionsByProject, arg.ProjectID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSuppression = `-- name: DeleteSuppression :exec
DELETE FROM suppressions
WHERE id = $1 AND project_id = $2
`

type DeleteSuppressionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteSuppression(ctx context.Context, arg DeleteSuppressionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSuppression, arg.ID, arg.ProjectID)
	return err
}

const deleteSuppressionByEmail = `-- name: DeleteSuppressionByEmail :exec
DELETE FROM suppressions
WHERE project_id = $1 AND email_normalized = LOWER($2)
`

type DeleteSuppressionByEmailParams struct {
	ProjectID uuid.UUID
	Lower     string
}

func (q *Queries) DeleteSuppressionByEmail(ctx context.Context, arg DeleteSuppressionByEmailParams) error {
	_, err := q.db.ExecContext(ctx, deleteSuppressionByEmail, arg.ProjectID, arg.Lower)
	return err
}

const isSuppressed = `-- name: IsSuppressed :one
SELECT EXISTS (
    SELECT 1 FROM suppressions
    WHERE project_id = $1 AND email_normalized = LOWER($2)
)
`

type IsSuppressedParams struct {
	ProjectID uuid.UUID
	Lower     string
}

func (q *Queries) IsSuppressed(ctx context.Context, arg IsSuppressedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isSuppressed, arg.ProjectID, arg.Lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSuppressionsByProject = `-- name: ListSuppressionsByProject :many
SELECT id, project_id, email_normalized, reason, source, created_at, last_seen_at FROM suppressions
WHERE project_id = $1
  AND ($2::text = '' OR reason = $2::text)
ORDER BY last_seen_at DESC
LIMIT $3 OFFSET $4
`

type ListSuppressionsByProjectParams struct {
	ProjectID uuid.UUID
	Column2   string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListSuppressionsByProject(ctx context.Context, arg ListSuppressionsByProjectParams) ([]Suppression, error) {
	rows, err := q.db.QueryContext(ctx, listSuppressionsByProject,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Suppression
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailNormalized,
			&i.Reason,
			&i.Source,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSuppression = `-- name: UpsertSuppression :one
INSERT INTO suppressions (project_id, email_normalized, reason, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, email_normalized) DO UPDATE
    SET last_seen_at = NOW(),
        reason = EXCLUDED.reason,
        source = COALESCE(EXCLUDED.source, suppressions.source)
RETURNING id, project_id, email_normalized, reason, source, created_at, last_seen_at
`

type UpsertSuppressionParams struct {
	ProjectID       uuid.UUID
	EmailNormalized string
	Reason          string
	Source          sql.NullString
}

func (q *Queries) UpsertSuppression(ctx context.Context, arg UpsertSuppressionParams) (Suppression, error) {
	row := q.db.QueryRowContext(ctx, upsertSuppression,
		arg.ProjectID,
		arg.EmailNormalized,
		arg.Reason,
		arg.Source,
	)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EmailNormalized,
		&i.Reason,
		&i.Source,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
