// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countTemplatesByProject = `-- name: CountTemplatesByProject :one
SELECT COUNT(*) FROM templates WHERE project_id = $1
`

func (q *Queries) CountTemplatesByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplatesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (project_id, name, subject, html_body, text_body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, subject, html_body, text_body, variables, created_at, updated_at
`

type CreateTemplateParams struct {
	ProjectID uuid.UUID
	Name      string
	Subject   string
	HtmlBody  string
	TextBody  string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate,
		arg.ProjectID,
		arg.Name,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1 AND project_id = $2
`

type DeleteTemplateParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, arg.ID, arg.ProjectID)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, project_id, name, subject, html_body, text_body, variables, created_at, updated_at FROM templates WHERE id = $1 AND project_id = $2
`

type GetTemplateByIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByID, arg.ID, arg.ProjectID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplatesByProject = `-- name: ListTemplatesByProject :many
SELECT id, project_id, name, subject, html_body, text_body, variables, created_at, updated_at FROM templates
WHERE project_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListTemplatesByProject(ctx context.Context, projectID uuid.UUID) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Subject,
			&i.HtmlBody,
			&i.TextBody,
			&i.Variables,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
    name = $3,
    subject = $4,
    html_body = $5,
    text_body = $6,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, subject, html_body, text_body, variables, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Subject   string
	HtmlBody  string
	TextBody  string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
