// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, provider, provider_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, name, plan, monthly_email_limit, monthly_emails_sent, monthly_reset_at, provider, provider_id, is_verified, is_banned, ban_reason, customer_id, subscription_id, subscription_status, plan_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash sql.NullString
	Name         string
	Provider     sql.NullString
	ProviderID   sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Plan,
		&i.MonthlyEmailLimit,
		&i.MonthlyEmailsSent,
		&i.MonthlyResetAt,
		&i.Provider,
		&i.ProviderID,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionStatus,
		&i.PlanChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, plan, monthly_email_limit, monthly_emails_sent, monthly_reset_at, provider, provider_id, is_verified, is_banned, ban_reason, customer_id, subscription_id, subscription_status, plan_changed_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Plan,
		&i.MonthlyEmailLimit,
		&i.MonthlyEmailsSent,
		&i.MonthlyResetAt,
		&i.Provider,
		&i.ProviderID,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionStatus,
		&i.PlanChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password_hash, name, plan, monthly_email_limit, monthly_emails_sent, monthly_reset_at, provider, provider_id, is_verified, is_banned, ban_reason, customer_id, subscription_id, subscription_status, plan_changed_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Plan,
		&i.MonthlyEmailLimit,
		&i.MonthlyEmailsSent,
		&i.MonthlyResetAt,
		&i.Provider,
		&i.ProviderID,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionStatus,
		&i.PlanChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, email, password_hash, name, plan, monthly_email_limit, monthly_emails_sent, monthly_reset_at, provider, provider_id, is_verified, is_banned, ban_reason, customer_id, subscription_id, subscription_status, plan_changed_at, created_at, updated_at FROM users WHERE provider = $1 AND provider_id = $2
`

type GetUserByProviderParams struct {
	Provider   sql.NullString
	ProviderID sql.NullString
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProvider, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Plan,
		&i.MonthlyEmailLimit,
		&i.MonthlyEmailsSent,
		&i.MonthlyResetAt,
		&i.Provider,
		&i.ProviderID,
		&i.IsVerified,
		&i.IsBanned,
		&i.BanReason,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionStatus,
		&i.PlanChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementEmailsSent = `-- name: IncrementEmailsSent :exec
UPDATE users SET monthly_emails_sent = monthly_emails_sent +1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementEmailsSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementEmailsSent, id)
	return err
}

const resetMonthlyUsage = `-- name: ResetMonthlyUsage :exec
UPDATE users SET monthly_emails_sent = 0,
    monthly_reset_at = date_trunc('month', NOW()) + INTERVAL '1 month',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetMonthlyUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetMonthlyUsage, id)
	return err
}

const updateUserPlan = `-- name: UpdateUserPlan :exec
UPDATE users SET plan = $2, plan_changed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateUserPlanParams struct {
	ID   uuid.UUID
	Plan string
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPlan, arg.ID, arg.Plan)
	return err
}
