// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimPendingDeliveries = `-- name: ClaimPendingDeliveries :many
UPDATE webhook_deliveries
SET status = 'inflight'
WHERE id IN (
    SELECT id FROM webhook_deliveries
    WHERE status = 'pending' AND next_attempt_at <= NOW()
    ORDER BY next_attempt_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
RETURNING id, webhook_id, event_type, payload, status, attempts, last_status_code, last_error, next_attempt_at, delivered_at, created_at
`

func (q *Queries) ClaimPendingDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastStatusCode,
			&i.LastError,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (project_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, url, secret, events, active, created_at
`

type CreateWebhookParams struct {
	ProjectID uuid.UUID
	Url       string
	Secret    string
	Events    []string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ProjectID,
		arg.Url,
		arg.Secret,
		pq.Array(arg.Events),
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		pq.Array(&i.Events),
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, webhook_id, event_type, payload, status, attempts, last_status_code, last_error, next_attempt_at, delivered_at, created_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID uuid.UUID
	EventType string
	Payload   json.RawMessage
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, createWebhookDelivery, arg.WebhookID, arg.EventType, arg.Payload)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastStatusCode,
		&i.LastError,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks
WHERE id = $1 AND project_id = $2
`

type DeleteWebhookParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, arg.ID, arg.ProjectID)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks
WHERE id = $1 AND project_id = $2
`

type GetWebhookParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, arg.ID, arg.ProjectID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		pq.Array(&i.Events),
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookForDispatchInternal = `-- name: GetWebhookForDispatchInternal :one
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks
WHERE id = $1
`

// INTERNAL USE ONLY. Lookup by webhook id without tenant scope.
// Only safe to call from the webhook dispatcher worker where the webhook id
// already comes from a verified webhook_deliveries row in the same project.
// NEVER call from a user-facing handler.
func (q *Queries) GetWebhookForDispatchInternal(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookForDispatchInternal, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		pq.Array(&i.Events),
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveWebhooksForEvent = `-- name: ListActiveWebhooksForEvent :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks
WHERE project_id = $1 AND active AND $2::text = ANY(events)
`

type ListActiveWebhooksForEventParams struct {
	ProjectID uuid.UUID
	EventType string
}

func (q *Queries) ListActiveWebhooksForEvent(ctx context.Context, arg ListActiveWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhooksForEvent, arg.ProjectID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			pq.Array(&i.Events),
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event_type, payload, status, attempts, last_status_code, last_error, next_attempt_at, delivered_at, created_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesParams struct {
	WebhookID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookDeliveries, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastStatusCode,
			&i.LastError,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByProject = `-- name: ListWebhooksByProject :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByProject(ctx context.Context, projectID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			pq.Array(&i.Events),
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE webhook_deliveries
SET status = 'failed',
    attempts = attempts + 1,
    last_status_code = $2,
    last_error = $3
WHERE id = $1
`

type MarkDeliveryFailedParams struct {
	ID             uuid.UUID
	LastStatusCode sql.NullInt32
	LastError      sql.NullString
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryFailed, arg.ID, arg.LastStatusCode, arg.LastError)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE webhook_deliveries
SET status = 'pending',
    attempts = attempts + 1,
    last_status_code = $2,
    last_error = $3,
    next_attempt_at = $4
WHERE id = $1
`

type MarkDeliveryRetryParams struct {
	ID             uuid.UUID
	LastStatusCode sql.NullInt32
	LastError      sql.NullString
	NextAttemptAt  time.Time
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryRetry,
		arg.ID,
		arg.LastStatusCode,
		arg.LastError,
		arg.NextAttemptAt,
	)
	return err
}

const markDeliverySuccess = `-- name: MarkDeliverySuccess :exec
UPDATE webhook_deliveries
SET status = 'delivered',
    attempts = attempts + 1,
    last_status_code = $2,
    delivered_at = NOW()
WHERE id = $1
`

type MarkDeliverySuccessParams struct {
	ID             uuid.UUID
	LastStatusCode sql.NullInt32
}

func (q *Queries) MarkDeliverySuccess(ctx context.Context, arg MarkDeliverySuccessParams) error {
	_, err := q.db.ExecContext(ctx, markDeliverySuccess, arg.ID, arg.LastStatusCode)
	return err
}
